### ISSUE TITLE
Ladder-only items in single player

### ISSUE THREAD

**Issue by narfbg** [Nasicus/d2-holy-grail#20]
I noticed that a lot of items have the following note:

> Originally found in Ladder only, but has been reportedly found in single player games.

Well, ladder only items can drop in single player ... not just reportedly, not just certain items, but for real.

I've seen confusion about this in other places too, so I'll explicitly say I'm not talking about PlugY, PoD or other mods - all ladder-only uniques (except the Annihilus and Hellfire Torch charms) and horadric cube recipes are available in vanilla single player, without any mods. Only the runewords and ubers (hence why no "torch & anni") don't work.

Oddly enough, the unique charms don't have the above note, while being ladder-only items. :)

**Comment by Nasicus** [comment]
Thanks for your comment.

I copied this description 1:1 from various sides (see here for the sources: https://github.com/Nasicus/d2-holy-grail/blob/master/server/src/ItemList.tsx.ts).

I didn't bother to correct these texts. However if you (or anyone other) likes he can change the texts (in the file above) and create a PR.

Imho we can remove all occurrences of:

- ladder
- version found (nobody cares about 1.09, 1.10 etc. anymore)

Honestly it would be fairly small change. So if nobody wants to do it I can also do it myself.
Just let me know :)

**Comment by narfbg** [comment]
I don't see any harm done by removing these. Should I submit a PR or should I wait for @squeek502's response?

**Comment by Nasicus** [comment]
Feel free to do a PR. I just mentioned him, because he is the only other contributor :D
