### ISSUE TITLE
Make it possible to disable the custom CTRL + F function

### ISSUE THREAD

**Issue by SightUp** [Nasicus/d2-holy-grail#23]
I used your Holy Grail every day! Big fan of it. Best way to track and log stuff. I would like to be able to use the cntrl+f function though. Reason why I like it more than your built in search function is because I can see what items are around it and how I am supposed to order things in my stash.

PS. Do you have a Discord you can share?

**Comment by Nasicus** [comment]
Thanks!

I see, I will add a setting to disable the `CTRL + F` soon.

Also you can find me on dbrunskis discord : https://discord.gg/j8w6gJ
Username is also `@Nasicus` there.

**Comment by Nasicus** [comment]
Implemented with d224e3a38842c6763b75b88b95d086a57f63b284
