### ISSUE TITLE
Fix wrong name of The General's Tan Do Li Ga

### ISSUE THREAD

**Issue by Nasicus** [Nasicus/d2-holy-grail#38]
Is currently:

`General's Tan Do Li Ga`

but should be

`The General's Tan Do Li Ga`

=> ensure backwards compatibility

**Comment by squeek502** [comment]
> Is currently:
> 
> `General's Tan Do Li Ga`

Where are you getting this? It currently is `The General's Tan Do Li Ga` as far as I can tell:

https://github.com/Nasicus/d2-holy-grail/blob/3dcd89d3f6e35a56559b49cd8ff7594178759cf7/client/src/common/seeds/HolyGrailSeedData.ts#L297

https://github.com/Nasicus/d2-holy-grail/blob/3dcd89d3f6e35a56559b49cd8ff7594178759cf7/server/src/ItemList.tsx.ts#L3594

and there is backwards compat:

https://github.com/Nasicus/d2-holy-grail/blob/3dcd89d3f6e35a56559b49cd8ff7594178759cf7/server/src/ItemList.tsx.ts#L10665-L10666

**Comment by Nasicus** [comment]
Haha. I'm such a fool. Looked at my own grail instead of in the code ;)
