### ISSUE TITLE
Marking perfect Rainbow Facets

### ISSUE THREAD

**Issue by narfbg** [Nasicus/d2-holy-grail#43]
So, I found a 5/5 Cold Up facet and went to the app to log the find, but when I submitted the changes, the star was appended to the Die one instead. If I bring up the modal window for either kind, they both show "Is Perfect" as ticked, and unmarking either one causes the same change to both.

Played around with the other elements a bit, and it appears that marking any of the Level Up ones as perfect alters the Die one instead. Weirdly enough, this didn't happen a couple of days ago when I marked a Lightning Up facet as perfect, but the difference is I already had the Die one marked previously (didn't unmark it after the #22 migration).

I realize this reads a bit hard, so here's a visual (left both cold ones unmarked) of my last saved state:

![Facets](https://user-images.githubusercontent.com/1058011/75271440-e3039e00-5804-11ea-85f7-7a292b2b94e4.png)

**Comment by narfbg** [comment]
> Played around with the other elements a bit, and it appears that marking any of the Level Up ones as perfect alters the Die one instead.

Just re-confirmed this - can't mark any of the Up facets as perfect on my new grail.

**Comment by Nasicus** [comment]
Sorry kind of forgot about this when I saw it the first time.

Should be fixed now. Let me know if it works :)

See the commit message for details.

**Comment by narfbg** [comment]
Had to do a hard refresh (Ctrl+F5), but after that it works, yes. Thank you! :+1:
