### ISSUE TITLE
Docker setup for production

### ISSUE THREAD

**Issue by imtbl** [Nasicus/d2-holy-grail#58]
First of all, thank you for this tool, very neat. :)

Since I needed an easy way to self-host this (and I prefer to deploy pretty much everything using containers these days), I created a simple Docker setup for production usage: <https://github.com/imtbl/d2-holy-grail-docker>

I thought I'd post it here in case that's something you (or other users) are interested in; feel free to use anything from that repository as you see fit in case you decide you want to provide an official Docker setup.

Please close this issue at your discretion; it's not really a feature request, but I wasn't sure if closing it right after opening would be appropriate.

**Comment by Nasicus** [comment]
Thanks.

If you want you can also move your files into a subfolder in the root of the repo... maybe something like "dockerized" or "containerized" - don't know about a good naming tbh.

Nice to see that people are still doingstuff :)

**Comment by imtbl** [comment]
Hey,

thank you for the offer of adding this Docker setup directly to this project. The only issue I see with that is the connection to Docker Hub; it requires the repository on GitHub to be linked (which only the repository maintainer can do), so you'd have to set up a Docker Hub account and a Docker Hub repository (since I can't give you access to mine). It's not hard and I could guide you through that if you have no experience with Docker Hub so far, but I'm not sure it's something you'd want to do (it might require manual interventions from time to time). If you do, I could adjust this setup (if it's in this repository I'd change it so the code gets copied directly from here instead of pulled in via HTTP) and make a PR.

The second option (linking to my repository) is of course much simpler and also viable, as I do plan to keep my Docker setup up to date in the future. I'd feel honored to have my repository included in the readme. If you want me to, I could prepare a PR that expands the readme, as you suggested.

Let me know what (if either) you'd prefer. Thanks!

**Comment by Nasicus** [comment]
I see. I actually have a Docker Hub account I think.

However I still prefer to go with the second option. So just add a section in the readme with a smal desription and link to you repo.

And thanks for contributing :)
