### ISSUE TITLE
Ability to Reset Passwords

### ISSUE THREAD

**Issue by javulas** [Nasicus/d2-holy-grail#62]
I lost the password to my account.

If you can help me out or just delete my username off the database as you said you could do for someone else in a previous Issue thread, I'd appreciate it. 

I've contacted you on Discord too, and I don't know which you'll see first but this might be a fine place to put this request just for the future.

Thank you very much!

**Comment by Nasicus** [comment]
Deleted.

Creating a password reset is not that easy, because you don't need to give any email on register. Therefore it's not really possible for me to do this automated.
