### ISSUE TITLE
Can't see any items

### ISSUE THREAD

**Issue by realTIMematrix** [Nasicus/d2-holy-grail#63]
Hi,

i can't see any items. I use Chrome and also tested it in incognito window. The picture can be loaded in a seperate tab, but not in the item frame. Any idea what I'm doing wrong?

<a href="https://gyazo.com/c46740549dd211f64bcd6bf5e1e57bf3"><img src="https://i.gyazo.com/c46740549dd211f64bcd6bf5e1e57bf3.png" alt="Image from Gyazo" width="617"/></a>

**Comment by Nasicus** [comment]
you're doing nothing wrong I think it has something to do with an invalid https certificate or https vs http...

**Comment by squeek502** [comment]
Here's a zip of all of the item images if you want to host them on the server instead of using d2tomb.com: [images.zip](https://github.com/Nasicus/d2-holy-grail/files/6039837/images.zip)

**Comment by Nasicus** [comment]
@squeek502 thanks I'm in holiday for 2 weeks, but I will do that after probably... I was always too lazy to get the images so far ;) :D

**Comment by Nasicus** [comment]
@realTIMematrix this has been fixed, the images are now directly served from the server (maybe you need to hard refresh press ctrl + f5)

@squeek502 thanks again mate!
