### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by Reudelbert** [Nasicus/d2-holy-grail#83]
I forgot my password, is there a way to reset it?

**Comment by Nasicus** [comment]
No. There are 2 things you  can do: 
- in the menu on the right you can clone your grail
- or you write me via discord and I can reset it to whatever you want

**Comment by Reudelbert** [comment]
I'd like to keep the same name. How can I find you on Discord?

**Comment by Nasicus** [comment]
I'm Nasicus in dbrunskis discord: https://discord.com/channels/398533219349299200
