### ISSUE TITLE
Enhancement: Add support for re-importing json exports

### ISSUE THREAD

**Issue by RecycleFix** [Nasicus/d2-holy-grail#94]
Add support to be able to import the exported json data, instead of only supporting the csv format.

**Comment by Nasicus** [comment]
You can actually just clone a grail in the menu on the right side which is basically the same thing.
If you're a programmer you could also just manually make the API request with your "json" to update the db, but when you do that you can also mess up your grail if you make a mistake :)

**Comment by RecycleFix** [comment]
> You can actually just clone a grail in the menu on the right side which is basically the same thing. If you're a programmer you could also just manually make the API request with your "json" to update the db, but when you do that you can also mess up your grail if you make a mistake :)

Do you have an example of how to use the API for that?
I can code that into my software to handle it when making changes

**Comment by RecycleFix** [comment]
I tried using this as an example: https://github.com/Nasicus/d2-holy-grail/issues/53#issuecomment-675767565

Using https://reqbin.com/ to do the api calls.

1) GET on https://d2-holy-grail.herokuapp.com/api/grail/USERNAME works and getting correct json back.

2) copy the json output from the GET call

3) adding in the password of the account, after version field
    "version": "1.1.0",
    "password":"CORRECT PASSWORD"

4) for one item, adding in wasFound true
.....
                    "elite": {
                        "Gimmershred": {"wasFound": true},
                        ......

5) changing it to do a PUT instead of GET and clicking Send.


Getting this returned:

HTTP/1.1 500 Internal Server Error
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 42
Etag: W/"2a-UrZ/U51lB8DyGqJYX+0W0Wpd+iE"
Date: Sat, 01 Jan 2022 18:12:32 GMT
Via: 1.1 vegur

{"type":"argument","argumentName":"grail"}

**Comment by squeek502** [comment]
@RecycleFix I believe you need a `"token"` key with a valid token as well. I looked into this and got something working a while back (but never fully finished it). Here's what I did to get a token (not verified to be fully accurate, this is just from my reading of the code; it's been a while since I wrote it):

Make a dummy `PUT` request to `/api/grail/<username>/settings` with the json:

```
{"password": "<password>", "settings": {}, "token": ""}
```

The response should have a `"correctToken"` key that you can then add to your `PUT` request as a `"token"` key. It should then succeed.

Here's the code in question for reference: https://github.com/squeek502/d2grailcheck/blob/f09b39e9cbb0023bdfd316454d2feac368752eb3/init.lua#L83-L108

**Comment by RecycleFix** [comment]
> @RecycleFix I believe you need a `"token"` key with a valid token as well. I looked into this and got something working a while back (but never fully finished it). Here's what I did to get a token (not verified to be fully accurate, this is just from my reading of the code; it's been a while since I wrote it):
> 
> Make a dummy `PUT` request to `/api/grail/<username>/settings` with the json:
> 
> ```
> {"password": "<password>", "settings": {}, "token": ""}
> ```
> 
> The response should have a `"correctToken"` key that you can then add to your `PUT` request as a `"token"` key. It should then succeed.
> 
> Here's the code in question for reference: https://github.com/squeek502/d2grailcheck/blob/f09b39e9cbb0023bdfd316454d2feac368752eb3/init.lua#L83-L108
> 
> The 500 response is unexpected though, there might be something else wrong as well.
> 
> EDIT: On second thought, I might be totally wrong about the `"token"`, since you might already get a valid token back with the `GET` request.

Thanks for your good explanation and idea.
But I just confirmed, the value of "correctToken" is the same as "token" from the GET request on /api/grail/<username> sadly

**Comment by squeek502** [comment]
Ok, I figured it out. There's a mismatch in the formats between the `GET` and `PUT` requests.

- In a `GET` request, it gives you the data with the keys `data`, `ethData`, and `runewordData`
- In a `PUT` request, it expects the keys `grail`, `ethGrail`, and `runewordGrail` instead

Swapping the keys `data` -> `grail`, `ethData` -> `ethGrail`, `runewordData` -> `runewordGrail` before sending the `PUT` request makes it work.

Relevant code (AFAICT):

- https://github.com/Nasicus/d2-holy-grail/blob/a3ca20779b84b4ffdda94bc15683f35d886aecdc/server/src/controllers/GrailController.ts#L83-L85
- https://github.com/Nasicus/d2-holy-grail/blob/bf5c9f13c1ee50d5871323517cec2c3b06d80f64/client/src/common/utils/Api.ts#L56-L63
- https://github.com/Nasicus/d2-holy-grail/blob/bf5c9f13c1ee50d5871323517cec2c3b06d80f64/client/src/common/definitions/api/IHolyGrailApiModel.ts#L9-L11
- and others probably, I'm not familiar with the codebase

**Comment by Nasicus** [comment]
Sorry I didn't answer here... I somehow missed the comment from 3td of december.

Nice that you figured it out hough.

For the future, the easiest way to figure this out, is by just going to the grail site, save something and look at the dev console:

![image](https://user-images.githubusercontent.com/1086065/147874971-fd600558-6e5c-4b21-b10b-82127c9825ac.png)
![image](https://user-images.githubusercontent.com/1086065/147874995-afee43f4-88d1-4a8a-b5d0-1486c967ae3c.png)

The API isn't really consistent and I never thought anyone was really going to use it outside the app itsel :P

**Comment by RecycleFix** [comment]
Thank you both.
Got it working now.

It helped renaming the keys.
